### ISSUE TITLE
Static IP gets overriden by Dynamic IP on Raspberry PI

### ISSUE THREAD

**Issue by aetilley** [sudomesh/bugs#12]
This is the one big hurdle I had to overcome when completing @jhpoelen 's wonderful walkthrough  (available [here](https://github.com/sudomesh/babeld-lab/blob/master/services_guide.md#use-case---raspberry-pi-as-wired-mesh-node-via-home-node)) on putting a Raspberry Pi + my MyNet600 on the Mesh.

For me the aforementioned tutorial went swimmingly until step 9, where one must reboot, unplug  from ethernet port 3 on the router and plug into port 2.  After doing this and SSHing into the raspberry pi (which took a few attempts to be successful, which might be related to the below problem), I was not able to ping any outside servers.  

Calling ifconfig for interface eth0, we found out that eth0 had been reassigned a dynamic IP address, an apparently was rendering ineffective the change to /etc/dhcpcd.conf in step 7.  (Note that calling hostname -I would actually print *both* ip addresses, but ifconfig would only display the dynamically assigned one.)

Making that change to /etc/dhcpcd.conf *adds* a static ip address, but there still seems to be some DHCP server continuously assigning a dynamic ip address upon reboot.  

My workaround for now is just:

1)  I have to manually delete the dynamic ip address via

sudo ip addr delete 172.22.0.9 dev eth0

2) After doing so, even though ifconfig eth0 updates immediately to the desired mesh ip address added in /etc/dhcpcd.conf, I still cannot ping the Internet *until*....

3) I unplug the ethernet cable from port 2 and then replug the ethernet cable back into port 2.   I have no idea why this would help, but it does. After this, I am able to ping the Internet *until*...

4)  I reboot the Raspberry Pi, at which time, the dynamic ip is reassigned, and I have to start over at step (1) above.

I have found a very long thread devoted to a similar problem at

https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=111709

although it does not seem like a clear solution is agreed upon.  In particular I do not have "allow-hotplug eth0" in my /etc/network/interfaces.

**Comment by jhpoelen** [comment]
thanks @aetilley . Referenced walk through currently lives https://github.com/sudomesh/babeld-lab/blob/master/services_guide.md#use-case---raspberry-pi-as-wired-mesh-node-via-home-node . 

Just wondering, what is the value of the /tmp/dhcp.leases on your pi ? (see step 5. in walk-through)

**Comment by aetilley** [comment]
One line:

1517285479 <some-IPv6> 100.65.27.106 Arthurs-MBP <some-other-IPv6>

**Comment by jhpoelen** [comment]
is this before or after the pi reboot leading to the double ip assignment of eth0 ?

**Comment by aetilley** [comment]
Both.  (I just rebooted just to verify.)

**Comment by jhpoelen** [comment]
@aetilley I cannot reproduce this using cow/chicken setup. 

It seems that the pi is somehow remembering previous dhcp leases, even though the router has no record of them. One thing I was thinking of is the ```persistent``` option in ```/etc/dhcpcd.conf``` on the pi. If you comment out the option, does the behavior still occur?

**Comment by aetilley** [comment]
@jhpoelen I'm afraid that doesn't didn't fix the problem, but I was able to find a solution.  I'm not sure if it's a good solution but it seems reasonable.

In my /etc/network/preferences, which looked like this:


```
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
      address 172.22.0.9
      netmask 255.255.255.0
      gateway 0.0.0.0

allow-hotplug wlan0
iface wlan0 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

allow-hotplug wlan1
iface wlan1 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```
I simply commented out the line that said `auto eth0`.

I will read up more on what the semantics of these files are.  I'd love to know what I'm doing here.

**Comment by aetilley** [comment]
I
