### ISSUE TITLE
report network status on peoplesopen website

### ISSUE THREAD

**Issue by paidforby** [sudomesh/bugs#14]
Can the status of the People's Open Network in Oakland, CA be presented on https://peoplesopen.net? I know there is [this monitoring page](https://monitor.sudomesh.org/cacti/graph.php?action=view&local_graph_id=217&rra_id=all) but I'm not sure if it is accurate. Sometimes it is difficult to tell if the network is running properly. Perhaps, when the network is "down", the background image on peoplesopen.net could be changed to something like [this](https://unsplash.com/photos/9GDa7nK_4q0) or another such image that implies some form of disaster? There could also be a page for the status of deployed exit nodes? Or the current number of active nodes? Just some ideas, would be interested to hear other suggestions.

**Comment by jhpoelen** [comment]
A monitoring webpage is now available and has been used via https://peoplesopen.net/monitor . Suggest to open new issues if we need to improve this at https://github.com/sudomesh/monitor , the associated github repo.
