### ISSUE TITLE
etherpad instance run as service on sudomesh server

### ISSUE THREAD

**Issue by paidforby** [sudomesh/bugs#3]
I've tried countless ways of trying to get etherpad running on the sudomesh server. It will run if I start it manually with `bin/run.sh` from the repo directory, but when I go through the steps to get it to run by default in the background it fails to start the service. Here's the most applicable guide I've found, https://help.ubuntu.com/community/Etherpad-liteInstallation  
At the step where it asks you to run: `sudo start etherpad-lite`  
It produces the output: `etherpad-lite stop/pre-start, process 32589`  

To reproduce bug:  
1. SSH into the sudomesh server as root  
2. run `sudo start etherpad-lite`  

Also, I've gone through all the debian and ubuntu options on this page https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service

They all produce the same error which makes me think it is a dependency error. I am running out of bandwidth dump any more time into this issue, so whoever wants who has access and wants to work on it can try to finish it. Going to open an issue in the etherpad repo also.

**Comment by paidforby** [comment]
Here's my issue with ether, https://github.com/ether/etherpad-lite/issues/3258

**Comment by Juul** [comment]
Fixed. All three startup scripts had different combinations of user/group to use for starting etherpad-lite and none of them lined up with existing users/groups and the file permissions. I changed all groups and users to etherpad-lite, created the etherpad-lite user and group, removed the etherpad user and group, changed all the file permissions and now it works.

I stopped it again for now since we're gettings:

```
[2017-09-25 11:20:29.972] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2017-09-25 11:20:32.962] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
```

We should fix those before starting it again.

**Comment by paidforby** [comment]
Thanks, I had tried so many different combinations of users and groups that I probably got confused at some point, half the examples ask you to create "etherpad" user/group and the other half suggest "etherpad-lite". I had tried starting over from scratch a few times with no luck.
