### ISSUE TITLE
upgrade peoplesopen.net droplet

### ISSUE THREAD

**Issue by bennlich** [sudomesh/bugs#32]
It's using ~80% of its memory and disk space.

@jnny do you want to coordinate a time to do this together?

**Comment by jhpoelen** [comment]
Suggest to publish builds on Zenodo or similar. This would avoid having to unnecessarily pay for storage space. Example see: https://zenodo.org/record/1205601 .

**Comment by jnny** [comment]
just saw this. i should get email notifications now @bennlich 

@jhpoelen zenodo looks awesome! looked over their policies and principles. +1 from me. maybe a loomio poll?

**Comment by jhpoelen** [comment]
http://about.zenodo.org

**Comment by jhpoelen** [comment]
Please note that https://peoplesopen.net/chat is giving a "bad gateway" error.

**Comment by eenblam** [comment]
@jhpoelen I was seeing the same, but seems to be up now. CC @bennlich .

**Comment by jnny** [comment]
@jhpoelen that page still doesn't say explicitly *what* zenodo is, only what they're "about" :) 

@bennlich sorry to bork the rocketchat instance! would be good to add to startup and add documentation to https://sudoroom.org/wiki/Mesh/Distributed_Services

**Comment by jhpoelen** [comment]
Ok - here's the cliff notes: zenodo is a no-fee open data publication platform hosted by CERN.

**Comment by bennlich** [comment]
> @bennlich just increased droplet size from $10 standard plan (2GB RAM, 1 vCPU, 50 GB SSD) to $40/mo standard (8GB RAM, 4 vCPUs, 160GB SSD) - thought I had increased it to the $20/mo plan at least! so that should suffice for awhile...

Woot! thanks @jnny! That's sweet. Hoping we won't have to restart etherpad now either.
