### ISSUE TITLE
peoplesopen.net/notes is borked

### ISSUE THREAD

**Issue by bennlich** [sudomesh/bugs#38]
I think I accidentally typed something into our /pad/p/notes etherpad that put it in a bad state. Whenever I try to load notes, I get this error in the console:

```
Uncaught Error: mismatch error setting raw text in setDocAText
```

Haven't had time to research much yet, but figured I'd start documenting here. Might be related to: https://github.com/ether/etherpad-lite/issues/3066.

Restarting etherpad-lite did not help. And other pads work fine.

**Comment by gobengo** [comment]
We're you pasting emoji? What makes you think it could have been something
you typed?

**Comment by bennlich** [comment]
It seemed to crash immediately after I tried pasting in the wiki minutes template.

My browser has been doing weird things when pasting that template--like removing all the newline characters. (Apparently this is a different etherpad-lite issue: https://github.com/ether/etherpad-lite/issues/2625.)

I saw an old issue where someone mentioned that a lack of a trailing newline could sometimes cause etherpad-lite to crash, but I think that was fixed.

**Comment by gobengo** [comment]
Thanks for added info

**Comment by bennlich** [comment]
While debugging this, I discovered a bunch of unused etherpad files and folders on the server. Going to delete them, as they make debugging extra confusing. Here's what I'm deleting:

- `/etc/init/etherpad.conf`
- `/etc/init.d/etherpad-lite`
- `/var/etherpad`
- `/usr/share/etherpad-lite`

All of this appears to be cruft from old installs. The real etherpad-lite is started with `/etc/init/etherpad-lite`, and lives in `/opt/etherpad/local/etherpad/etherpad-lite`.

**Comment by gobengo** [comment]
* We fixed peoplesopen.net/notes (by deleting and recreating the pad)
  * `curl "https://peoplesopen.net/pad/api/1/deletePad?apikey=$apikey&padID=notes"`
  * apikey is in ssh://peoplesopen.net:/opt/etherpad/local/etherpad/etherpad-lite/APIKEY.txt

**Comment by gobengo** [comment]
@bennlich  please close issue if all good?

**Comment by bennlich** [comment]
Yes! Hooray! Also deleted `/home/etherpad-lite/local/etherpad`. So many red herrings...
