### ISSUE TITLE
https://monitor.peoplesopen.net certificate expired 

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/bugs#6]
Looks like https://monitor.peoples.net certificate expired 5 Nov 2017.

![screenshot from 2017-11-14 17-38-22](https://user-images.githubusercontent.com/1084872/32814197-c39bcae8-c962-11e7-8e00-119cbb3203b7.png)

**Comment by otakup0pe** [comment]
Looks like the cert on https://monitor.sudomesh.org/ has been restored (and is good until april) but the cacti server is broken now 😬

**Comment by jhpoelen** [comment]
@otakup0pe thanks for checking . . . please open a separate issue on cacti server. Would be great if you can help figure out how to expose some monitoring stats to the "big" internet on the peoplesopen.net website.

**Comment by jhpoelen** [comment]
@otakup0pe please see https://github.com/sudomesh/peoplesopen-front/issues/10
