### ISSUE TITLE
404 for https://disaster.radio/learn/userguides in https://disaster.radio/learn/firmware/

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/bugs#7]
to reproduce:

go to https://disaster.radio/learn/firmware/ 

click on User Guides 

observe 404.

**Comment by jhpoelen** [comment]
@sierkje @paidforby applied fix for broken link, but didn't find instructions on how to deploy. Suggest to add instructions on how to deploy to https://github.com/sudomesh/disaster-radio-website.

**Comment by paidforby** [comment]
Nice catch, forgot about that bug! 
on sudomesh server:
```
git pull --rebase
gulp
```
you only caught one of the "user-guides" errors. I'll fix the other, rebase, and add instructions to the readme.
