### ISSUE TITLE
how to put a service on the mesh?

### ISSUE THREAD

**Issue by paidforby** [sudomesh/bugs#9]
a la  @jhpoelen proposal for an operator's manual [in sudowrt issue 118](https://github.com/sudomesh/sudowrt-firmware/issues/118), I would also like to document the process for getting "my first service" on the mesh. All the way from conception (i.e. "I have this idea..." or "we should have this...") to implementation (get a computer, pi, router... install this package or that...) to maintenance ("am I getting updates?" and "who's maintaining this?").

I understand an attempt was made at this with [mesh-playbooks](https://github.com/sudomesh/mesh-playbooks), so maybe that can be updated or revised. Any advice?

**Comment by Juul** [comment]
If you want to put something on the mesh the easiest way is to connect it
to the public wifi SSID of a mesh node or connect it to the public ethernet
port on a home node. It will get a mesh IP address and be accessible from
the mesh. If you want a static IP then you can look at the dnsmasq setup on
the home node and see that a few IPs for each home node are reserved,
simply set one of those IPs as static for the device.

I agree that we should document how to put something on the mesh directly
by running babeld on it.

**Comment by paidforby** [comment]
Ports 1, 2 and 4 do not appear to be providing ip addresses. Issue opened in sudowrt-firmware (https://github.com/sudomesh/sudowrt-firmware/issues/121)

**Comment by jhpoelen** [comment]
Can confirm that public port (or port 4) does hand out IPs some of the time. However, I can't seem to reproduce on other router, probably due to my lack of understanding of dhcp caching (the second service I tried to configure got a 172.30.* address first, and keeps associating with it). 

Also, the extender node ips for a home node can be found here:
```
# cat /etc/config/notdhcpserver 
config server
  option enabled '1'
  list addresses 'eth0.1=100.65.20.66/26'
  list addresses 'eth0.2=100.65.20.67/26'
  option hook_script '/opt/notdhcpserver/hook.sh'
  option ssl_cert '/etc/uhttpd.crt'
  option ssl_key '/etc/uhttpd.key'
  option timeout_length '180'
```

**Comment by jhpoelen** [comment]
the ip pattern seems to be: home node ip +1 and +2 . In this case, home node mesh ip was 100.65.20.65 .

**Comment by jhpoelen** [comment]
@paidforby please close this issue if the changes in https://github.com/sudomesh/babeld-lab/commit/fd82ab93c4db8944c1abcb3273223541d3b39f89 fix this.

**Comment by paidforby** [comment]
@jhpoelen thanks for the services guide, works for me and others, assuming the exit node it up...
